### PR TITLE
Fixed plant texture issues

### PR DESCRIPTION
**Pull request by ChaosTherum**
There were some capitalization issues in the xml

### CODE REVIEW

**Comment by simon-82** [comment]
oh wow
That is so odd. already changed all these myself
Seems like the changes did not get commited. 
Which is strange cause git should see the changed filenames.

I'll do this myself. But thanks for bringing this to my attention.
If you want to help us, come join the rimworld modding slack. We all hang out there

**Comment by simon-82** [comment]
aha! 
TIL git is not case sensitive by default

http://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git

So I had all the files and xmls match loacally, but they didnt actually commit. I changed the git settings for the repo now and it should sync.
Again thanks for finding this! 
And I hope to see you on the Modding Slack if you want to help :+1: 

http://rimworldmod-slackin.herokuapp.com/

**Comment by ChaosTherum** [comment]
Yeah that's why I changed the xml didn't realize that you could make git case sensitive. You would think it would be case sensitive since it was made by linus and linux is case sensitive.

**Comment by simon-82** [comment]
yea well I made a mess now. Not a good idea to make it case sensitive lol
Trying to clean it up... oops :cold_sweat:

**Pull request closed without merging**
