### PR TITLE
Tlupdates, Gourmet Garden

### PR DESCRIPTION
**Pull request by TLHeart**
Added in gourmet garden, first pass of meals balance.

Added in CCL vanilla tweaks which removes the vanilla standing lamps, without editing the core.

Felt that herbal meds were way too difficult to obtain.. increased plant harvest to 5 from 1.  Also changed herb med to medicine, to 4 herb + cloth = 3 medicine.. 75*4=300. 

Changed loom to crafting from tailoring.

### CODE REVIEW

**Comment by simon-82** [comment]
wow that's a lot of stuff you changed.
On the first look, the ccl vanilla tweaks need to be added only in parts. The recipes often use Steel, instead of steelbars as in the modpack. Better to integrate that stuff manually. 
Artillery shells for example, no need for that whole file as we have it defined in the modpack.
The standing lamp you comment out in the modpack and add the vanilla tweaks instead of just implementing it in the modpack, why? 

I put most of the stuff into the modpack folder to not have to jump between files defining the same over and over again. This is one case. You have the standing lamp in core defined, then you need to know that it gets redefined in ccl tweaks. Gets confusing very very fast. 

Not to mention what happens when the core gets updates again with alpha 13. 
I document all changes to core files to be able to update the modpack in the future.
When there are changes to core, The file has "vanilla start" and "vanilla end" in it or in thingcategories it has a big "added" comment. Very important for updates. 

The no-raid storyteller - sure, why not add it - can also be put into storyteller def in the modpack to the others we already have there.

And the nutrition changes. 
I took out the meal defs for nutrition because that's only complicating things with no benefit. Almost all plants would need to be balanced accordingly to have the right amount of nutrition. You can end up with 1 simple meal needing like literally 100 of one kind to make. Need to be very careful with that. Did you test for this?

I also needed to change the "cooking supplies" thing category to have "Food" as parent, you made "FoodRaw" the parent. This leads to meals (simple, fine, lavish) made from sugar or flour. Doesn't make sense.

I redid most of the workgivers myself just today. Includes the switch of loom to crafting

I can't pick and choose parts easily because that's all in one commit.
Alright, leave the pull request open please. I can merge some stuff with the command line options. 

Do you have different branches now? As in, can you send a pull request with only the gourmet garden additions?
Gourmet garden we can't automatically merge, too. We have bread + texture already for example. 
All food textures are in textures/Items. Why add new folder for only some food?
And did you add literally everything from gourmet garden? We talked about some additions to have more fine/lavish meals. Better pick and choose what to add that has real benefits to the gameplay. 
No need to have 100s of things that do just the same imo. 
It's the same as adding all guns from ProjectArmory for example. Really need 50 pistols that all have the same stats, just a different texture?

**Comment by TLHeart** [comment]
On the vanilla tweaks, only need the lamps part... was not sure how you wanted that handled though.It was to show you it could be done, without modifying the core.

 I intentional had the cooking ingredients set to raw food so that they could be used in the meal recipes, with the nutritional values. It is your modpack, do what you want... Yes I use every recipe from the vegetable garden and gourmet garden in my play. Adds variety. And I did change what many meals provides in nutrition, joy, thoughts. I put the gourmet garden textures as a separate file as I prefer smaller groups of related items, instead of ONE HUGE file to hunt through.

I honestly had plans to add even more meals for variety.... but I see that is not something you want. oh well. I will forget about sharing those.

Might as well just have generic meat, with generic veg and generic fruit then.

I could say the same thing about beer, apple cider, wine, strawberry wine, sake,.... whiskey, they are all the same, and NOT needed in the game, since they add NOTHING, but variety. Just have generic alcohol.

Why have all those additional plants, to be grown if your are not going to be adding in specific meals to use those foods? All those additional plants add NOTHING to the game otherwise.

WE have a big difference in what adds to game play.

**Comment by simon-82** [comment]
Well, ok first off I gotta say I am sorry how my message turned out.
I had a really bad day yesterday and shouldn't have looked at github at all.
You spent a lot of time on that pull request and I was just criticizing you with no reason. 
I hope you can accept that apology and I am very thankful for your commitment to making the modpack better. 

That being said, the only problem was a lack of communication between us. 
Up until now, you just did a few tweaks here and there. And that was perfectly fine. 
And I wasn't sure if you even want to do anything more. Seeing the work you put in now makes me think you DO want to be a part of this project. 
If so, we need to talk about stuff first, then add it. I don't want you working on something, then me saying I don't like it afterwards. 

To quickly summarize the differences we have to clarify before integrating:
1. Adding small mods (like ccl tweaks, storytellers). I think they should be integrated in the modpack folder as much as possible. This keeps the numbers of folders /files down and makes it easier to update stuff when the core gets updated again.
2. File management in the modpack folder. I think stuff should be grouped together as much as possible. It is just a personal thing though. Idealy now that so much food stuff is added, we should have a folder with all the food in there (meals, raw, everything).
3. The nutrition. I really want to keep that out. The base for simple meal is 10 raw food and it scales from there. That's easy enough to manage and tweak if needed without starting to calculate the numbers. 
4. Cooking ingredients for meals. If you look at it that way, you have to decide if you want to grind all your wheat to flour or use it for meals. I think that makes it more interesting. Otherwise just set the bill to make flour forever and done. One could argue that the wheat plant should give flour from the field directly then. All it does is add more work.
5. Variety of food/alcohol/sweets/beverages. You are right, the alcohol that's in the modpack now doesn't have that much variety in terms of hediffgivers / thoughts / joykinds. I want to work on that to make everything have a different effect. You make some very good points about that issue. Having thought about it, yes you are right. Adding everything IS good for variety. The more different the effects are is also good though.  

Again sorry for my harsh message. I didn't mean to be rude. If you are still interested, I would love to hear your opinions on the points I listed.

**Comment by TLHeart** [comment]
Communicating via messages is always difficult between people who do not know each other.

I have good days, with lots of energy, and I have bad days. 
1. Adding small items, I can see the benefit of adding it directly in. But then what is small? The lines of code, or what it does to the game? Hard to define.
2. I personally like folders for items, like the gourmet food items, makes it easier to verify I have called the correct texture... But I can also see where trying to find the right texture, for an item among many folders, instead of one large one could be difficult.
3. Nutrition may be a large part of Alpha 13...if tynan continues down the path he started, and has planned. I disagree totally with the scaling of meals from 10, it does not work as a lavish meal does not waste 50% of the ingredients. Meats do not have the same nutrition as vegetables. 
   But it is your mod pack, and you are the one who will be tasked with the update to alpha 13, so no nutrition values.
4. really don't understand your comment here. Flour is ground from a possible 4 ingredients, which if ground then can not be used in other recipes like alcohol, or porridge. So there is a choice to be made.  Don't want cooking ingredients used for simple meals, easy to exclude them.

But flour and water, do make a simple meal, called hard tack.  Inexpensive and long-lasting, it was and is used for sustenance in the absence of perishable foods, commonly during long sea voyages and military campaigns.

Side note, All you did was add work to the herbal medicine for xerigum. And I may say badly in my opinion, each plant only produces 1, and it takes 5 to make one herbal med... which have a potency of 75%, but it takes 5 herbal meds to make 1 medicine with a potency of 100%... 375 = 100 so it takes a minimum of 25 plants of xerigum to produce 1 medicine.

I do agree with there is no need to have 5 or 50 items that all do the same thing, with just a different texture. I was not doing that. I was trying to make  interesting food choices from all the different crops, and get away from the 10 = 1 meal. But I guess that is just too complicated for those who play rimworld for the combat, and want easy quick decision making. And it may be.

Here is how I like to play; https://ludeon.com/forums/index.php?topic=16419.0

and here is another colony; https://ludeon.com/forums/index.php?topic=2824.msg179691#msg179691

But I am in the minority of people who enjoy the laid back base building, food and animal management. So many want the harsh, cant survive, die to raids experience.

**Comment by simon-82** [comment]
1. Need to decide for each mod. Basically if the mod is easy to integrate into the modpack folder, I just do it. If it has crafting in it, it would always go into the modpack (see steelbars vs steel). If it is self-contained I try to keep it on its own for easy updates. I kept out graphical mods and factions mainly. Although factions have their weapons rebalanced (needed for CR).
2. I am all for folders if they make sense. There are folders for "Graphic_StackCount" items now and for "Graphic_Random" items. Having a folder for all food items would be ok. Just looking for basic organisation. That's why I was not very happy having parts of the textures for food in one folder, parts in the other. 
3. Alright, nutrition it is then. You convinced me. Now we have to come up with a system that works and scales for all the plants and food that is in right now. Let's try and keep the gourmet garden out for this first and work on a solid system first. Have you seen the top part of the file "plants_cultivated" in thingdefs? Something like that. 
   There is a post in the modpack forum thread with a good idea:
   Quote: "I suggest to add new req for fine and lavish meal. If you make better meal ask better corps that will give motivation for players" 
   Sounds like a nice idea to gate fine and lavish meals behind say "tier 1" and "tier 2" plants. 
   I will think about it a little and make an issue here on github for that. 
   Getting away from the 10 raw = 1 meal is ok and interesting, but it needs to be easy to understand for the player. And planting the better crops = better / more meals could be a way to make that happen. 
4. Good point. This ties into 3. 

Xerigium: Sure, lets buff the plant to yield more. Maybe 3-5 per plant. Maybe try with 3 and lower the time for growing.

**Pull request closed without merging**
