### PR TITLE
Mulch Tweak

### PR DESCRIPTION
**Pull request by TLHeart**
Added the ability to mix ingredients to make mulch. Feels much better to me, than having to only use 40 of one item.

It appears git hub also includes my next update to the cooking.  

Still confuses me what those other 3 are though.

### CODE REVIEW

**Comment by TLHeart** [comment]
please don't merge the cooking items tweeks... cant prepare the fish.

**Comment by simon-82** [comment]
If you do a pull request, it always wants to sync up both branches to the most up-to-date one.
See what I wrote [here](https://github.com/simon-82/ModVarietyPack/issues/10).
If you want me to only pull in let' say up to the mulch tweak, you would need a branch in your fork that is at that specific place and ask me to pull in that one. 

As for the other 3: 
- First one is an automated "pull request". The branch TLUpdates tracks the changes made to my dev branch and pulls them in. In this case, it pulled in the grass tweak, cause that was missing from your branch. It is doing that because you set it up to track my branch. It's not doing that by default.
- The second one is me updating my master branch to do a release. So I merged all of our changes we did in the dev branch into master, because I was sure these changes are ok and worth releasing. That way, the master branch stays at a "stable" state and we can mess around in dev as much as we want. 
- The third one is kinda strange, cause you are now pulling stuff in manually from my master to your branch which is tracking dev. 

Remote tracking is not a bad thing, don't get me wrong. But it's also a little advanced. I wasn't saying anything because I thought you know why you set it up that way. 

For the other projects I am contributing to (this is not my only account here), I do it that way: 
- I have my fork set to remote track the unstable/dev/update (most projects have this) branch of the project. Now I have a clean base for myself that is always up-to-date. 
- I have then several branches going off my fork. One is the branch I am confident with and want to merge. I send pull requests only from this branch.
- If I feel like doing more, I do that in another branch. As you can see here, if I would go on changing the branch the pull request was sent from, the request would get updated everytime I change something.  

But by no way is this the way you HAVE to do it. Everybody does it how they feel most comfortable with. If you want to see how huge projects with tons of contributers handle it, take a look for example at [xbmc](https://github.com/xbmc) or [the muppets](https://github.com/TheMuppets)

**Comment by TLHeart** [comment]
Thanks for putting up with my newbieness... at times it is like learning a new language.  And I only understand about half of what you said there, as I set the github desk top up with defaults. Everything I have worked on is compartmentalized, hand the code up, and never see it again, unless they want something changed.

**Comment by simon-82** [comment]
Well, github is based on working together. It is a community thing. Without it the open source community would not be where it is today.
Oh btw, you like to work on the food stuff it seems. 
All changes here are good. 
If you want to step it up a bit, I was thinking of bringing in some alternatives to the fine meal. Because all there is at the top end of the food production is basically the fine meal. 
There is [gourmet garden](https://ludeon.com/forums/index.php?topic=12934.0), an add-on to veg garden we have already. It has some nice ideas, like burgers made from bread and meat and so on. 
Implementaion of these high.end meals needs also some nice effects for the guy that eats them though. 
For implementing a burger for example it needs:
- new thingdef "Burger" (in ThingDefs)
- new recipe (recipe in RecipeDefs and unlock of the recipe in AdvancedResearchDefs)
- the effects the burger gives when eaten (joy in JoyGiverDefs or maybe even direct bonuses in HediffDefs / HediffGiverSetDefs)

There are plenty of examples alreaddy in the code how it is done.

**Comment by TLHeart** [comment]
I like gourmet garden, have been playing with it for months. And he has the thought codes mainly using the fine and lavish meal. Also I feel a better balance of ingredients to meal balance than the lavish meal does.

I play along until I hit something that does not seem right, then I investigate. The disorganization to food and cooking has always been a big problem for me, so yea, I saw an opportunity to effect some organization to it. 
Learn something new every day, no I had not considered the trader kinddef, so investigated, and tested.
Checked the traderdefs, and since all but one of the food item changes I made are still in the root foods, it did not change anything in there.  The only big change there is they can not sell you dead whole fish corpses, just like they can't sell you a dead muffalo.

The change to fishing rod did not break the fishing pier, the colonist walks over fishes, catches fish and returns... just made it possible to create an outfit bill that includes the fishing rod, instead of force wearing it. And the apparel trader can buy and sell the fishing rod.

**Comment by TLHeart** [comment]
upon further thinking I discovered a problem I had created with the category changes with fish... that traders were unable to bring full fish for the aquaculture basins... so I added the corpses to the bulk resources trader... seems like a logical place. And traders need to be able to bring fish corpses for those maps that don't have any water.

Also discovered the aqua hopper was not refrigerated, so added the CCL comp so that it is.

**Pull request merged**
